project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - slides.qmd
    - live_sessions.qmd
        
website:
  title: ""
  search: false

  navbar:
    search: false  
    link-external-newwindow: true
    title: BUSI 721 901
    file: index.qmd
    right:

      - text: Code Binder
        href: https://mybinder.org/v2/gh/kerryback/2023-721-901-binder.git/HEAD

      - text: Notebook Repo
        href: https://github.com/kerryback/2023-721-901-binder

      - text: Slide Decks
        file: slides.qmd

      - text: Live Session Recordings
        file: live_sessions.qmd

      - text: Learn Investments Dashboard
        href: https://bbcx-investments.com

      
format: 
  html:
    theme: cosmo
    scss: styles.css
    link-external-newwindow: true
    



